// Seed data — the admin panel can add/edit dishes in Firebase.
// If Firebase 'dishes' node is empty, we fall back to these.
export const seedDishes = [
  {
    id: 'd1',
    name: 'Butter Chicken',
    category: 'North Indian',
    description: 'Creamy tomato gravy with tender chicken chunks, cooked in rich butter and aromatic spices.',
    price: 320,
    emoji: '🍛',
    veg: false,
    rating: 4.8,
    time: '25 min',
    available: true,
    image: ''
  },
  {
    id: 'd2',
    name: 'Paneer Tikka',
    category: 'Starters',
    description: 'Marinated cottage cheese cubes grilled to perfection with bell peppers and onions.',
    price: 250,
    emoji: '🧀',
    veg: true,
    rating: 4.7,
    time: '20 min',
    available: true,
    image: ''
  },
  {
    id: 'd3',
    name: 'Margherita Pizza',
    category: 'Italian',
    description: 'Classic hand-tossed pizza with fresh mozzarella, tomato sauce and basil.',
    price: 299,
    emoji: '🍕',
    veg: true,
    rating: 4.6,
    time: '30 min',
    available: true,
    image: ''
  },
  {
    id: 'd4',
    name: 'Chicken Biryani',
    category: 'North Indian',
    description: 'Fragrant basmati rice layered with spiced chicken, saffron, and caramelized onions.',
    price: 350,
    emoji: '🍚',
    veg: false,
    rating: 4.9,
    time: '35 min',
    available: true,
    image: ''
  },
  {
    id: 'd5',
    name: 'Veg Burger',
    category: 'Fast Food',
    description: 'Crispy patty with fresh lettuce, tomato, cheese and our special house sauce.',
    price: 149,
    emoji: '🍔',
    veg: true,
    rating: 4.4,
    time: '15 min',
    available: true,
    image: ''
  },
  {
    id: 'd6',
    name: 'Pasta Alfredo',
    category: 'Italian',
    description: 'Creamy white sauce pasta with mushrooms, garlic and parmesan.',
    price: 279,
    emoji: '🍝',
    veg: true,
    rating: 4.5,
    time: '20 min',
    available: true,
    image: ''
  },
  {
    id: 'd7',
    name: 'Masala Dosa',
    category: 'South Indian',
    description: 'Crispy rice crepe filled with spiced potato masala, served with chutneys.',
    price: 129,
    emoji: '🥞',
    veg: true,
    rating: 4.7,
    time: '15 min',
    available: true,
    image: ''
  },
  {
    id: 'd8',
    name: 'Gulab Jamun',
    category: 'Desserts',
    description: 'Soft milk dumplings soaked in warm cardamom sugar syrup.',
    price: 99,
    emoji: '🍮',
    veg: true,
    rating: 4.8,
    time: '10 min',
    available: true,
    image: ''
  },
  {
    id: 'd9',
    name: 'Chocolate Brownie',
    category: 'Desserts',
    description: 'Warm fudgy brownie served with vanilla ice cream and chocolate sauce.',
    price: 149,
    emoji: '🍫',
    veg: true,
    rating: 4.9,
    time: '10 min',
    available: true,
    image: ''
  },
  {
    id: 'd10',
    name: 'Mango Lassi',
    category: 'Beverages',
    description: 'Refreshing yogurt drink blended with sweet Alphonso mango pulp.',
    price: 89,
    emoji: '🥭',
    veg: true,
    rating: 4.6,
    time: '5 min',
    available: true,
    image: ''
  },
  {
    id: 'd11',
    name: 'Chicken 65',
    category: 'Starters',
    description: 'Spicy deep-fried chicken bites tossed with curry leaves and green chilies.',
    price: 229,
    emoji: '🍗',
    veg: false,
    rating: 4.7,
    time: '20 min',
    available: true,
    image: ''
  },
  {
    id: 'd12',
    name: 'Cold Coffee',
    category: 'Beverages',
    description: 'Blended iced coffee with vanilla ice cream topped with chocolate syrup.',
    price: 129,
    emoji: '🥤',
    veg: true,
    rating: 4.5,
    time: '5 min',
    available: true,
    image: ''
  },
];

export const categories = [
  { id: 'all', name: 'All', emoji: '🍽️' },
  { id: 'North Indian', name: 'North Indian', emoji: '🍛' },
  { id: 'South Indian', name: 'South Indian', emoji: '🥞' },
  { id: 'Italian', name: 'Italian', emoji: '🍕' },
  { id: 'Fast Food', name: 'Fast Food', emoji: '🍔' },
  { id: 'Starters', name: 'Starters', emoji: '🍢' },
  { id: 'Desserts', name: 'Desserts', emoji: '🍰' },
  { id: 'Beverages', name: 'Beverages', emoji: '🥤' },
];
